<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('bill_entries', function (Blueprint $table) {
            $table->id();
            $table->date('room_rent_date')->default(date("Y-m-d H:i:s"));
            $table->date('room_rent_from')->default(date("Y-m-d H:i:s"));
            $table->date('room_rent_to')->default(date("Y-m-d H:i:s"));
            $table->integer('room_rent_total_days')->default(0);
            $table->double('room_rent_amount')->default(0);
            $table->double('room_rent_total_amount')->default(0);
            $table->string('room_rent_file')->nullable();
            $table->date('icu_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('icu_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('icu_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('icu_charges_total_days')->default(0);
            $table->double('icu_charges_amount')->default(0);
            $table->double('icu_charges_total_amount')->default(0);
            $table->string('icu_charges_file')->nullable();
            $table->date('nursing_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('nursing_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('nursing_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('nursing_charges_total_days')->default(0);
            $table->double('nursing_charges_amount')->default(0);
            $table->double('nursing_charges_total_amount')->default(0);
            $table->string('nursing_charges_file')->nullable();
            $table->date('diet_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('diet_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('diet_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('diet_charges_total_days')->default(0);
            $table->double('diet_charges_amount')->default(0);
            $table->double('diet_charges_total_amount')->default(0);
            $table->string('diet_charges_file')->nullable();
            $table->date('rmo_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('rmo_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('rmo_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('rmo_charges_total_days')->default(0);
            $table->double('rmo_charges_amount')->default(0);
            $table->double('rmo_charges_total_amount')->default(0);
            $table->string('rmo_charges_file')->nullable();
            $table->date('administration_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('administration_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('administration_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('administration_charges_total_days')->default(0);
            $table->double('administration_charges_amount')->default(0);
            $table->double('administration_charges_total_amount')->default(0);
            $table->string('administration_charges_file')->nullable();
            $table->date('iv_fluids_date')->default(date("Y-m-d H:i:s"));
            $table->date('iv_fluids_from')->default(date("Y-m-d H:i:s"));
            $table->date('iv_fluids_to')->default(date("Y-m-d H:i:s"));
            $table->integer('iv_fluids_total_days')->default(0);
            $table->double('iv_fluids_amount')->default(0);
            $table->double('iv_fluids_total_amount')->default(0);
            $table->string('iv_fluids_file')->nullable();
            $table->date('blood_transfusion_date')->default(date("Y-m-d H:i:s"));
            $table->date('blood_transfusion_from')->default(date("Y-m-d H:i:s"));
            $table->date('blood_transfusion_to')->default(date("Y-m-d H:i:s"));
            $table->integer('blood_transfusion_total_days')->default(0);
            $table->double('blood_transfusion_amount')->default(0);
            $table->double('blood_transfusion_total_amount')->default(0);
            $table->string('blood_transfusion_file')->nullable();
            $table->date('injection_date')->default(date("Y-m-d H:i:s"));
            $table->date('injection_from')->default(date("Y-m-d H:i:s"));
            $table->date('injection_to')->default(date("Y-m-d H:i:s"));
            $table->integer('injection_total_days')->default(0);
            $table->double('injection_amount')->default(0);
            $table->double('injection_total_amount')->default(0);
            $table->string('injection_file')->nullable();
            $table->date('medical_practitioners_fees_date')->default(date("Y-m-d H:i:s"));
            $table->date('medical_practitioners_fees_from')->default(date("Y-m-d H:i:s"));
            $table->date('medical_practitioners_fees_to')->default(date("Y-m-d H:i:s"));
            $table->integer('medical_practitioners_fees_total_days')->default(0);
            $table->double('medical_practitioners_fees_amount')->default(0);
            $table->double('medical_practitioners_fees_total_amount')->default(0);
            $table->string('medical_practitioners_fees_file')->nullable();
            $table->date('specialists_visit_date')->default(date("Y-m-d H:i:s"));
            $table->date('specialists_visit_from')->default(date("Y-m-d H:i:s"));
            $table->date('specialists_visit_to')->default(date("Y-m-d H:i:s"));
            $table->integer('specialists_visit_total_days')->default(0);
            $table->double('specialists_visit_amount')->default(0);
            $table->double('specialists_visit_total_amount')->default(0);
            $table->string('specialists_visit_file')->nullable();
            $table->date('consultants_visit_date')->default(date("Y-m-d H:i:s"));
            $table->date('consultants_visit_from')->default(date("Y-m-d H:i:s"));
            $table->date('consultants_visit_to')->default(date("Y-m-d H:i:s"));
            $table->integer('consultants_visit_total_days')->default(0);
            $table->double('consultants_visit_amount')->default(0);
            $table->double('consultants_visit_total_amount')->default(0);
            $table->string('consultants_visit_file')->nullable();
            $table->date('surgeon_fees_visit_date')->default(date("Y-m-d H:i:s"));
            $table->date('surgeon_fees_visit_from')->default(date("Y-m-d H:i:s"));
            $table->date('surgeon_fees_visit_to')->default(date("Y-m-d H:i:s"));
            $table->integer('surgeon_fees_visit_total_days')->default(0);
            $table->double('surgeon_fees_visit_amount')->default(0);
            $table->double('surgeon_fees_visit_total_amount')->default(0);
            $table->string('surgeon_fees_visit_file')->nullable();
            $table->date('anaesthetist_date')->default(date("Y-m-d H:i:s"));
            $table->date('anaesthetist_from')->default(date("Y-m-d H:i:s"));
            $table->date('anaesthetist_to')->default(date("Y-m-d H:i:s"));
            $table->integer('anaesthetist_total_days')->default(0);
            $table->double('anaesthetist_amount')->default(0);
            $table->double('anaesthetist_total_amount')->default(0);
            $table->string('anaesthetist_file')->nullable();
            $table->date('ot_assistant_date')->default(date("Y-m-d H:i:s"));
            $table->date('ot_assistant_from')->default(date("Y-m-d H:i:s"));
            $table->date('ot_assistant_to')->default(date("Y-m-d H:i:s"));
            $table->integer('ot_assistant_total_days')->default(0);
            $table->double('ot_assistant_amount')->default(0);
            $table->double('ot_assistant_total_amount')->default(0);
            $table->string('ot_assistant_file')->nullable();
            $table->date('physiotherapy_date')->default(date("Y-m-d H:i:s"));
            $table->date('physiotherapy_from')->default(date("Y-m-d H:i:s"));
            $table->date('physiotherapy_to')->default(date("Y-m-d H:i:s"));
            $table->integer('physiotherapy_total_days')->default(0);
            $table->double('physiotherapy_amount')->default(0);
            $table->double('physiotherapy_total_amount')->default(0);
            $table->string('physiotherapy_file')->nullable();
            $table->date('pharmacy_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('pharmacy_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('pharmacy_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('pharmacy_charges_total_days')->default(0);
            $table->double('pharmacy_charges_amount')->default(0);
            $table->double('pharmacy_charges_total_amount')->default(0);
            $table->string('pharmacy_charges_file')->nullable();
            $table->date('medicines_date')->default(date("Y-m-d H:i:s"));
            $table->date('medicines_from')->default(date("Y-m-d H:i:s"));
            $table->date('medicines_to')->default(date("Y-m-d H:i:s"));
            $table->integer('medicines_total_days')->default(0);
            $table->double('medicines_amount')->default(0);
            $table->double('medicines_total_amount')->default(0);
            $table->string('medicines_file')->nullable();
            $table->date('drugs_date')->default(date("Y-m-d H:i:s"));
            $table->date('drugs_from')->default(date("Y-m-d H:i:s"));
            $table->date('drugs_to')->default(date("Y-m-d H:i:s"));
            $table->integer('drugs_total_days')->default(0);
            $table->double('drugs_amount')->default(0);
            $table->double('drugs_total_amount')->default(0);
            $table->string('drugs_file')->nullable();
            $table->date('diagnostic_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('diagnostic_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('diagnostic_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('diagnostic_charges_total_days')->default(0);
            $table->double('diagnostic_charges_amount')->default(0);
            $table->double('diagnostic_charges_total_amount')->default(0);
            $table->string('diagnostic_charges_file')->nullable();
            $table->date('lab_tests_date')->default(date("Y-m-d H:i:s"));
            $table->date('lab_tests_from')->default(date("Y-m-d H:i:s"));
            $table->date('lab_tests_to')->default(date("Y-m-d H:i:s"));
            $table->integer('lab_tests_total_days')->default(0);
            $table->double('lab_tests_amount')->default(0);
            $table->double('lab_tests_total_amount')->default(0);
            $table->string('lab_tests_file')->nullable();
            $table->date('investigation_date')->default(date("Y-m-d H:i:s"));
            $table->date('investigation_from')->default(date("Y-m-d H:i:s"));
            $table->date('investigation_to')->default(date("Y-m-d H:i:s"));
            $table->integer('investigation_total_days')->default(0);
            $table->double('investigation_amount')->default(0);
            $table->double('investigation_total_amount')->default(0);
            $table->string('investigation_file')->nullable();
            $table->date('imaging_investigation_date')->default(date("Y-m-d H:i:s"));
            $table->date('imaging_investigation_from')->default(date("Y-m-d H:i:s"));
            $table->date('imaging_investigation_to')->default(date("Y-m-d H:i:s"));
            $table->integer('imaging_investigation_total_days')->default(0);
            $table->double('imaging_investigation_amount')->default(0);
            $table->double('imaging_investigation_total_amount')->default(0);
            $table->string('imaging_investigation_file')->nullable();
            $table->date('other_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('other_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('other_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('other_charges_total_days')->default(0);
            $table->double('other_charges_amount')->default(0);
            $table->double('other_charges_total_amount')->default(0);
            $table->string('other_charges_file')->nullable();
            $table->date('anaesthesia_date')->default(date("Y-m-d H:i:s"));
            $table->date('anaesthesia_from')->default(date("Y-m-d H:i:s"));
            $table->date('anaesthesia_to')->default(date("Y-m-d H:i:s"));
            $table->integer('anaesthesia_total_days')->default(0);
            $table->double('anaesthesia_amount')->default(0);
            $table->double('anaesthesia_total_amount')->default(0);
            $table->string('anaesthesia_file')->nullable();
            $table->date('blood_date')->default(date("Y-m-d H:i:s"));
            $table->date('blood_from')->default(date("Y-m-d H:i:s"));
            $table->date('blood_to')->default(date("Y-m-d H:i:s"));
            $table->integer('blood_total_days')->default(0);
            $table->double('blood_amount')->default(0);
            $table->double('blood_total_amount')->default(0);
            $table->string('blood_file')->nullable();
            $table->date('oxygen_date')->default(date("Y-m-d H:i:s"));
            $table->date('oxygen_from')->default(date("Y-m-d H:i:s"));
            $table->date('oxygen_to')->default(date("Y-m-d H:i:s"));
            $table->integer('oxygen_total_days')->default(0);
            $table->double('oxygen_amount')->default(0);
            $table->double('oxygen_total_amount')->default(0);
            $table->string('oxygen_file')->nullable();
            $table->date('operation_theatre_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('operation_theatre_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('operation_theatre_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('operation_theatre_charges_total_days')->default(0);
            $table->double('operation_theatre_charges_amount')->default(0);
            $table->double('operation_theatre_charges_total_amount')->default(0);
            $table->string('operation_theatre_charges_file')->nullable();
            $table->date('surgical_appliances_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('surgical_appliances_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('surgical_appliances_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('surgical_appliances_charges_total_days')->default(0);
            $table->double('surgical_appliances_charges_amount')->default(0);
            $table->double('surgical_appliances_charges_total_amount')->default(0);
            $table->string('surgical_appliances_charges_file')->nullable();
            $table->date('implants_for_surgical_procedures_date')->default(date("Y-m-d H:i:s"));
            $table->date('implants_for_surgical_procedures_from')->default(date("Y-m-d H:i:s"));
            $table->date('implants_for_surgical_procedures_to')->default(date("Y-m-d H:i:s"));
            $table->integer('implants_for_surgical_procedures_total_days')->default(0);
            $table->double('implants_for_surgical_procedures_amount')->default(0);
            $table->double('implants_for_surgical_procedures_total_amount')->default(0);
            $table->string('implants_for_surgical_procedures_file')->nullable();
            $table->date('prosthetics_devices_date')->default(date("Y-m-d H:i:s"));
            $table->date('prosthetics_devices_from')->default(date("Y-m-d H:i:s"));
            $table->date('prosthetics_devices_to')->default(date("Y-m-d H:i:s"));
            $table->integer('prosthetics_devices_total_days')->default(0);
            $table->double('prosthetics_devices_amount')->default(0);
            $table->double('prosthetics_devices_total_amount')->default(0);
            $table->string('prosthetics_devices_file')->nullable();
            $table->date('other_devices_date')->default(date("Y-m-d H:i:s"));
            $table->date('other_devices_from')->default(date("Y-m-d H:i:s"));
            $table->date('other_devices_to')->default(date("Y-m-d H:i:s"));
            $table->integer('other_devices_total_days')->default(0);
            $table->double('other_devices_amount')->default(0);
            $table->double('other_devices_total_amount')->default(0);
            $table->string('other_devices_file')->nullable();
            $table->date('implant_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('implant_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('implant_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('implant_charges_total_days')->default(0);
            $table->double('implant_charges_amount')->default(0);
            $table->double('implant_charges_total_amount')->default(0);
            $table->string('implant_charges_file')->nullable();
            $table->date('other_consumable_items_date')->default(date("Y-m-d H:i:s"));
            $table->date('other_consumable_items_from')->default(date("Y-m-d H:i:s"));
            $table->date('other_consumable_items_to')->default(date("Y-m-d H:i:s"));
            $table->integer('other_consumable_items_total_days')->default(0);
            $table->double('other_consumable_items_amount')->default(0);
            $table->double('other_consumable_items_total_amount')->default(0);
            $table->string('other_consumable_items_file')->nullable();
            $table->date('payable_consumables_date')->default(date("Y-m-d H:i:s"));
            $table->date('payable_consumables_from')->default(date("Y-m-d H:i:s"));
            $table->date('payable_consumables_to')->default(date("Y-m-d H:i:s"));
            $table->integer('payable_consumables_total_days')->default(0);
            $table->double('payable_consumables_amount')->default(0);
            $table->double('payable_consumables_total_amount')->default(0);
            $table->string('payable_consumables_file')->nullable();
            $table->date('non_payable_consumables_date')->default(date("Y-m-d H:i:s"));
            $table->date('non_payable_consumables_from')->default(date("Y-m-d H:i:s"));
            $table->date('non_payable_consumables_to')->default(date("Y-m-d H:i:s"));
            $table->integer('non_payable_consumables_total_days')->default(0);
            $table->double('non_payable_consumables_amount')->default(0);
            $table->double('non_payable_consumables_total_amount')->default(0);
            $table->string('non_payable_consumables_file')->nullable();
            $table->date('ambulance_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('ambulance_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('ambulance_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('ambulance_charges_total_days')->default(0);
            $table->double('ambulance_charges_amount')->default(0);
            $table->double('ambulance_charges_total_amount')->default(0);
            $table->string('ambulance_charges_file')->nullable();
            $table->date('registration_admission_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('registration_admission_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('registration_admission_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('registration_admission_charges_total_days')->default(0);
            $table->double('registration_admission_charges_amount')->default(0);
            $table->double('registration_admission_charges_total_amount')->default(0);
            $table->string('registration_admission_charges_file')->nullable();
            $table->date('package_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('package_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('package_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('package_charges_total_days')->default(0);
            $table->double('package_charges_amount')->default(0);
            $table->double('package_charges_total_amount')->default(0);
            $table->string('package_charges_file')->nullable();
            $table->date('gipsa_ppn_packages_date')->default(date("Y-m-d H:i:s"));
            $table->date('gipsa_ppn_packages_from')->default(date("Y-m-d H:i:s"));
            $table->date('gipsa_ppn_packages_to')->default(date("Y-m-d H:i:s"));
            $table->integer('gipsa_ppn_packages_total_days')->default(0);
            $table->double('gipsa_ppn_packages_amount')->default(0);
            $table->double('gipsa_ppn_packages_total_amount')->default(0);
            $table->string('gipsa_ppn_packages_file')->nullable();
            $table->date('bhc_packages_date')->default(date("Y-m-d H:i:s"));
            $table->date('bhc_packages_from')->default(date("Y-m-d H:i:s"));
            $table->date('bhc_packages_to')->default(date("Y-m-d H:i:s"));
            $table->integer('bhc_packages_total_days')->default(0);
            $table->double('bhc_packages_amount')->default(0);
            $table->double('bhc_packages_total_amount')->default(0);
            $table->string('bhc_packages_file')->nullable();
            $table->date('other_date')->default(date("Y-m-d H:i:s"));
            $table->date('other_from')->default(date("Y-m-d H:i:s"));
            $table->date('other_to')->default(date("Y-m-d H:i:s"));
            $table->integer('other_total_days')->default(0);
            $table->double('other_amount')->default(0);
            $table->double('other_total_amount')->default(0);
            $table->string('other_file')->nullable();
            $table->date('opd_charges_date')->default(date("Y-m-d H:i:s"));
            $table->date('opd_charges_from')->default(date("Y-m-d H:i:s"));
            $table->date('opd_charges_to')->default(date("Y-m-d H:i:s"));
            $table->integer('opd_charges_total_days')->default(0);
            $table->double('opd_charges_amount')->default(0);
            $table->double('opd_charges_total_amount')->default(0);
            $table->string('opd_charges_file')->nullable();
            $table->date('wellness_date')->default(date("Y-m-d H:i:s"));
            $table->date('wellness_from')->default(date("Y-m-d H:i:s"));
            $table->date('wellness_to')->default(date("Y-m-d H:i:s"));
            $table->integer('wellness_total_days')->default(0);
            $table->double('wellness_amount')->default(0);
            $table->double('wellness_total_amount')->default(0);
            $table->string('wellness_file')->nullable();
            $table->double('hospital_amount')->default(0);
            $table->double('hospital_amount_file')->default(0);
            $table->double('bhc_amount')->default(0);
            $table->double('bhc_total_amount')->default(0);
            $table->string('bhc_file')->default(0);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('bill_entries');
    }
};
